### ISSUE TITLE
Cannot match a top level directory if using nested configuration

### ISSUE THREAD

**Issue by hadashiA** [staltz/switch-path#19]
I saw strange behaviour. switchPath didn't match a top level directory following at:

``` javascript
    switchPath('/bar', {
      '/bar': 123,
      '/home': {
        '/': 456,
        '/foo': 789
      }
    });

// => { path: null, value: null }
```

In this case, `/home` and `/home/foo` is working fine.
Any idea?

**Comment by bloodyKnuckles** [comment]
It appears the problem is with this condition: https://github.com/staltz/switch-path/blob/master/src/index.js#L99-L100

```
if (!child.path !== null &&
  betterMatch(nestedPath, matchedPath))
{
```

`betterMatch` only compares number of characters in the paths. This is allowing sub paths in non-matching sibling's nested configurations to be compared as if sibling was compatible with the `sourcePath`.

Added path validation:

```
if (!child.path !== null &&
  validatePath(nestedPath, matchedPath) &&
  betterMatch(nestedPath, matchedPath))
{
```

See pull request: https://github.com/staltz/switch-path/pull/21

**Comment by hadashiA** [comment]
@bloodyKnuckles Thanks for your help. You did a great job!
